name: Master_CI
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: |
          npm install

      - name: Run test with jest
        run: |
          npm run build
          npm test -- --forceExit --detectOpenHandles

  deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: |
          sudo npm install -g aws-cdk
          npm install

      - name: CDK Deploy
        run: |
          cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_ACCOUNT_REGION }}
